### ISSUE TITLE
electronパッケージへの依存

### ISSUE THREAD

**Issue by weyk** [kujirahand/nadesiko3electron#1]
依存(dependency)にelectronが入っているのですが、electronのチュートリアルによると
electronは開発時依存(devDependency)で良いようです。
この差の分が、パッケージを作成した際に含まれるモジュールに
影響するようなので、結構なサイズ差になりそうです。
（electronをdevDependencyに移してbuild:winするとnode_modulesにはshell-quoteしか
入ってこない）

**Comment by kujirahand** [comment]
@weyk ご指摘ありがとうございました！
修正しました。node_modulesの中が、shell-quoteだけになりました。
